version: '3'

services:
  pg-db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/entrypoint.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    networks:
      - stack

  bakckend:
    image: node:18.15-alpine3.16
    restart: always
    ports:
      - 80:3000
    volumes:
      - .:/app
    working_dir: '/app'
    command: 'yarn start'
    networks:
      - stack
    links:
      - pg-db
    depends_on:
      - pg-db

networks:
  stack:
    driver: bridge
